name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name:  install go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      - name: install golangci-lint
        run:
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.54.2
      - name: checkout code
        uses: actions/checkout@v3
      - name: lint code
        run: make lint
  test:
    runs-on: ubuntu-20.04
    steps:
      - name:  install go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.x
      - name: checkout code
        uses: actions/checkout@v3
      - name: run tests
        run: make test
